export const SET_FILTER = "SET_FILTER";
export const RIMBLE_ADD_PROGRESSALERT = "RIMBLE_ADD_PROGRESSALERT";
export const RIMBLE_TOGGLE_PROGRESSALERT = "RIMBLE_TOGGLE_PROGRESSALERT";
export const RIMBLE_SET_PROGRESSALERT_STATUS =
  "RIMBLE_SET_PROGRESSALERT_STATUS";
export const RIMBLE_SET_PROGRESSALERT_TX_HASH =
  "RIMBLE_SET_PROGRESSALERT_TX_HASH";
