// Transaction ProgressAlert actions
export const SET_FILTER = "SET_FILTER";
export const RIMBLE_ADD_PROGRESSALERT = "RIMBLE_ADD_PROGRESSALERT";
export const RIMBLE_TOGGLE_PROGRESSALERT = "RIMBLE_TOGGLE_PROGRESSALERT";
export const RIMBLE_SET_PROGRESSALERT_STATUS =
  "RIMBLE_SET_PROGRESSALERT_STATUS";
export const RIMBLE_SET_PROGRESSALERT_TX_HASH =
  "RIMBLE_SET_PROGRESSALERT_TX_HASH";
export const RIMBLE_UPDATE_PROGRESSALERT_CONTENT =
  "RIMBLE_UPDATE_PROGRESSALERT_CONTENT";

// Transaction Modal actions
export const RIMBLE_TOGGLE_NETWORK_MODAL = "RIMBLE_TOGGLE_NETWORK_MODAL";
export const RIMBLE_TOGGLE_TX_START_MODAL = "RIMBLE_TOGGLE_TX_START_MODAL";
export const RIMBLE_TOGGLE_TX_PENDING_MODAL = "RIMBLE_TOGGLE_TX_PENDING_MODAL";
export const RIMBLE_TOGGLE_TX_SUCCESS_MODAL = "RIMBLE_TOGGLE_TX_SUCCESS_MODAL";
export const RIMBLE_TOGGLE_TX_ERROR_MODAL = "RIMBLE_TOGGLE_TX_ERROR_MODAL";
export const RIMBLE_TOGGLE_TX_LOW_BALANCE_MODAL =
  "RIMBLE_TOGGLE_TX_LOW_BALANCE_MODAL";
export const RIMBLE_TOGGLE_TX_ACTIVITY_MODAL =
  "RIMBLE_TOGGLE_TX_ACTIVITY_MODAL";
